import type { Metadata } from "next";
import { Bebas_Neue, Inter, Poppins, Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialMedia from "@/components/SocialMedia";

// Títulos / Headlines
const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-title",
});

// Texto principal / UI
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// CTAs / Botões
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-cta",
});

// Editorial / artigos
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`
          ${bebasNeue.variable}
          ${inter.variable}
          ${poppins.variable}
          ${lora.variable}
          antialiased
        `}
      >
        <SocialMedia />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
